# Generated by Django 5.0.3 on 2024-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=30)),
                ('doctor_specialization', models.CharField(max_length=30)),
                ('doctor_phone', models.IntegerField()),
                ('doctor_email', models.EmailField(max_length=30)),
                ('doctor_image', models.ImageField(upload_to='image')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
