# Generated by Django 5.0.3 on 2024-07-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_alter_doctormodel_doctor_phone'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
                ('department_image', models.ImageField(upload_to='image')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='doctor_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment_date', models.DateField()),
                ('Appointment_time', models.TimeField()),
                ('status', models.CharField(max_length=30)),
                ('Patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctormodel')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='doctor_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.departmentmodel'),
        ),
    ]
