# Generated by Django 5.0.3 on 2024-07-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_departmentmodel_doctormodel_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departmentmodel',
            table='doctordepartment',
        ),
    ]
