# Generated by Django 5.0.3 on 2024-07-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_alter_departmentmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormodel',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='booking_time',
            new_name='time',
        ),
    ]
