# Generated by Django 5.0.3 on 2024-07-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0007_rename_days_doctormodel_end_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormodel',
            old_name='end_days',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='start_days',
            new_name='start_date',
        ),
    ]
